name: RunFiles - Dufs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  make-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install makeself
        run: sudo apt-get update && sudo apt-get install -y makeself curl

      - name: Download dufs ipks
        run: |
          chmod +x runfilesbuilder/shell/dufs.sh
          ./runfilesbuilder/shell/dufs.sh

      - name: Copy install.sh to each platform dir
        run: |
          chmod +x runfilesbuilder/shell/install.sh
          cp runfilesbuilder/shell/install.sh x86_64/install.sh
          cp runfilesbuilder/shell/install.sh aarch64_generic/install.sh
          cp runfilesbuilder/shell/install.sh aarch64_cortex-a53/install.sh
          cp runfilesbuilder/shell/install.sh arm_cortex-a7_neon-vfpv4/install.sh

      - name: Extract version and pack
        id: pack
        run: |
          mkdir -p output

          DUFS_IPK=$(ls aarch64_generic/dufs_*.ipk | head -n 1)
          VERSION=$(basename "$DUFS_IPK" | sed -n 's/^dufs_\([^-]*-[^_]*\)_.*$/\1/p')

          if [ -z "$VERSION" ]; then
            echo "Cannot extract version"
            exit 1
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT

          for PLATFORM in x86_64 aarch64_generic aarch64_cortex-a53 arm_cortex-a7_neon-vfpv4; do
            makeself "$PLATFORM" "output/dufs-${VERSION}_${PLATFORM}.run" \
              "Dufs ${PLATFORM} Installer v${VERSION}" ./install.sh
          done

      - name: Upload run files to release
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: "Dufs-${{ steps.pack.outputs.version }}"
          name: "Dufs-${{ steps.pack.outputs.version }}"
          files: output/*.run
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
